mysql-import error reporting added #25

diff --git a/.docker/bin/dsh b/.docker/bin/dsh
--- a/.docker/bin/dsh
+++ b/.docker/bin/dsh
@@ -410,7 +410,13 @@ mysql_import ()
 	get_mysql_connect sql_connect
 	echo "Importing $filename into database 'drupal'..."
 	run "pv ./$pathdiff/$filename | "$sql_connect
-	echo "mysql-import finished"
+	local res
+	res=$?
+	if [ $res -eq 0 ]; then
+		echo "mysql-import finished"
+	else
+		echo "mysql-import failed"
+	fi
 }
 
 # Shortcut to run drush cc ... on site
